import type { Metadata } from 'next'
import Link from 'next/link'
import { Breadcrumbs } from '@/components/Breadcrumbs'
import DeliveryPlanner from '@/components/DeliveryPlanner'
import { CONTACTS, DELIVERY_ITEMS } from '@/lib/site-content'
import { absoluteUrl } from '@/lib/seo'

export const metadata: Metadata = { title: 'Доставка и оплата', description: 'Условия поставки промышленного оборудования Akvera: транспортные компании, самовывоз, безналичная оплата и документы.', alternates: { canonical: absoluteUrl('/delivery') } }

export default function DeliveryPage() {
  return <main className="bg-[#f4f5f7]"><div className="mx-auto max-w-[1440px] px-5 pb-16 pt-6 sm:px-8 lg:px-12"><Breadcrumbs items={[{ label: 'Главная', href: '/' }, { label: 'Доставка и оплата' }]} /><section className="overflow-hidden rounded-3xl bg-[#28313d] p-7 text-white sm:p-10 lg:p-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#77cb98]">Akvera</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">Доставка без лишних согласований</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/65">Подберём удобный способ получения, подготовим документы и согласуем все условия до отгрузки.</p><div className="mt-8 flex flex-wrap gap-3"><a href={`tel:${CONTACTS.phone.replace(/[^\d+]/g, '')}`} className="rounded-xl bg-accent px-5 py-3 text-sm font-semibold text-white transition hover:bg-accent-hover">Позвонить менеджеру</a><Link href="/#request" className="rounded-xl border border-white/20 px-5 py-3 text-sm font-semibold text-white transition hover:bg-white/10">Рассчитать поставку</Link></div></section><DeliveryPlanner /><section className="mt-8 grid gap-4 lg:grid-cols-3">{DELIVERY_ITEMS.map((item) => <article key={item.title} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-black/[.04]"><h2 className="text-xl font-semibold text-[#28313d]">{item.title}</h2><ul className="mt-5 space-y-3">{item.points.map((point) => <li key={point} className="flex gap-3 text-sm leading-6 text-[#697482]"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />{point}</li>)}</ul></article>)}</section><section className="mt-8 grid gap-5 rounded-3xl bg-[#eaf0eb] p-6 sm:p-8 lg:grid-cols-[1.2fr_.8fr]"><div><p className="text-xs font-semibold uppercase tracking-wide text-accent">Как проходит поставка</p><ol className="mt-5 grid gap-4 sm:grid-cols-3">{['Подтверждаем состав заказа', 'Согласовываем срок и способ доставки', 'Передаём оборудование и документы'].map((item, index) => <li key={item} className="text-sm leading-6 text-[#52606f]"><span className="mb-2 block text-lg font-semibold text-[#28394c]">0{index + 1}</span>{item}</li>)}</ol></div><div className="rounded-2xl bg-white p-5"><h2 className="text-lg font-semibold text-[#28313d]">Нужна поставка под объект?</h2><p className="mt-2 text-sm leading-6 text-[#697482]">Пришлите список оборудования или спецификацию — подготовим коммерческое предложение.</p><Link href="/#request" className="mt-5 inline-flex rounded-xl bg-[#28394c] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#344a62]">Оставить заявку</Link></div></section></div></main>
}
